name: vomie
description: A Flutter-based IMDB app.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animations: ^2.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.30.1
  flutter_localizations:
    sdk: flutter
  introduction_screen: ^3.0.2
  kiwi: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  flutter_gen_runner: ^4.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

flutter_gen:
  output: .dart_tool/flutter_gen
