name: vomie
description: A Flutter-based IMDB app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  firebase_auth: ^3.3.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.30.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
