name: xoomie
description: A Flutter-based IMDB app.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  animations: ^2.0.3
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.30.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  google_sign_in: ^5.3.3
  hydrated_bloc: ^8.1.0
  introduction_screen: ^3.0.2
  kiwi: ^4.0.2
  material_design_icons_flutter: ^5.0.6595
  olive: ^0.0.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_thin.ttf
          weight: 100
        - asset: assets/fonts/poppins_extra_light.ttf
          weight: 200
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_black.ttf
          weight: 900

flutter_gen:
  output: .dart_tool/flutter_gen
  integrations:
    flutter_svg: true
